name: Caitrin
favicon: null
layout_spectrum: 0.6294759933371097
typography_spectrum: 0.4266583377029747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6907289829105139
  lightness: 0.7918442802038044
  saturation: 0.05800617509521544
  rhythmicContrast: 0.9336466689128429
purpose: []
