name: Caitrin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4266583377029747
title: 'Graphic Designer + Radness Expert '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#813d76'
    - '#2c0965'
    - '#896475'
    - '#cdaccf'
    - '#cb355a'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
