name: Caitrin
favicon: null
layout_spectrum: 0.74052
typography_spectrum: 0.35493
title: I am Caitrin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070f12'
    - '#f4eefa'
    - '#7895a7'
    - '#804935'
    - '#c89579'
  brandStrength: 0.0625
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
